#!/bin/bash
set -eu

# OpenDesk Nextcloud entrypoint for UBI9
# Handles first-run installation, upgrades, and runtime configuration
# Adapted from the official Nextcloud Docker entrypoint for RHEL9

user="apache"
group="apache"

# --- Helper Functions ---

version_greater() {
    [ "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1" ]
}

# Support reading secrets from files (VAR_FILE pattern)
file_env() {
    local var="$1"
    local fileVar="${var}_FILE"
    local def="${2:-}"
    local varValue=$(printenv "$var" || true)
    local fileVarValue=$(printenv "$fileVar" || true)

    if [ -n "$varValue" ] && [ -n "$fileVarValue" ]; then
        echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
        exit 1
    fi

    if [ -n "$varValue" ]; then
        export "$var"="$varValue"
    elif [ -n "$fileVarValue" ]; then
        export "$var"="$(cat "$fileVarValue")"
    elif [ -n "$def" ]; then
        export "$var"="$def"
    fi
}

run_as() {
    if [ "$(id -u)" = 0 ]; then
        su -p "$user" -s /bin/bash -c "$1"
    else
        bash -c "$1"
    fi
}

# Run path for hook scripts
run_hook_scripts() {
    local hook_dir="/docker-entrypoint-hooks.d/$1"
    if [ -d "$hook_dir" ]; then
        echo "=> Searching for hook scripts (*.sh) in \"$hook_dir\""
        local found=0
        for f in "$hook_dir"/*.sh; do
            [ -f "$f" ] || continue
            found=1
            echo "==> Running $f"
            if [ -x "$f" ]; then
                "$f"
            else
                bash "$f"
            fi
        done
        if [ "$found" -eq 0 ]; then
            echo "==> Skipped: the \"$1\" folder is empty (or does not exist)"
        fi
    else
        echo "=> Searching for hook scripts (*.sh) to run, located in the folder \"$hook_dir\""
        echo "==> Skipped: the \"$1\" folder is empty (or does not exist)"
    fi
}

# --- Write PHP config from environment variables ---
write_php_config() {
    local php_memory_limit="${PHP_MEMORY_LIMIT:-512M}"
    local php_upload_limit="${PHP_UPLOAD_LIMIT:-512M}"
    local php_opcache_mem="${PHP_OPCACHE_MEMORY_CONSUMPTION:-128}"

    cat > /etc/php.d/99-nextcloud.ini <<PHPEOF
; Generated by OpenDesk Nextcloud entrypoint
memory_limit = ${php_memory_limit}
upload_max_filesize = ${php_upload_limit}
post_max_size = ${php_upload_limit}
max_execution_time = 3600
max_input_time = 3600

[opcache]
opcache.enable = 1
opcache.memory_consumption = ${php_opcache_mem}
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 1
opcache.save_comments = 1
opcache.jit = 0
PHPEOF
}

# --- Configure Redis session handler ---
configure_redis_session() {
    if [ -n "${REDIS_HOST:-}" ]; then
        local redis_port="${REDIS_HOST_PORT:-6379}"
        local redis_pass="${REDIS_HOST_PASSWORD:-}"
        local session_path

        if [ "${REDIS_HOST:0:1}" = "/" ]; then
            # Unix socket
            session_path="${REDIS_HOST}?database=0"
        else
            session_path="tcp://${REDIS_HOST}:${redis_port}?database=0"
        fi

        if [ -n "$redis_pass" ]; then
            session_path="${session_path}&auth=${redis_pass}"
        fi

        cat > /etc/php.d/99-redis-session.ini <<REDISEOF
; Redis session handler - generated by entrypoint
session.save_handler = redis
session.save_path = "${session_path}"
REDISEOF
    fi
}

# --- Generate Nextcloud config snippets from environment ---
write_config_snippets() {
    local config_dir="/var/www/html/config"
    mkdir -p "$config_dir"

    # S3 object store configuration
    if [ -n "${OBJECTSTORE_S3_BUCKET:-}" ]; then
        cat > "$config_dir/s3.config.php" <<'S3EOF'
<?php
$CONFIG = array(
    'objectstore' => array(
        'class' => '\\OC\\Files\\ObjectStore\\S3',
        'arguments' => array(
            'bucket'       => getenv('OBJECTSTORE_S3_BUCKET'),
            'autocreate'   => strtolower(getenv('OBJECTSTORE_S3_AUTOCREATE') ?: 'false') === 'true',
            'key'          => getenv('OBJECTSTORE_S3_KEY') ?: '',
            'secret'       => getenv('OBJECTSTORE_S3_SECRET') ?: '',
            'hostname'     => getenv('OBJECTSTORE_S3_HOST') ?: '',
            'port'         => (int)(getenv('OBJECTSTORE_S3_PORT') ?: 443),
            'use_ssl'      => strtolower(getenv('OBJECTSTORE_S3_SSL') ?: 'true') !== 'false',
            'region'       => getenv('OBJECTSTORE_S3_REGION') ?: 'us-east-1',
            'use_path_style' => strtolower(getenv('OBJECTSTORE_S3_USEPATH_STYLE') ?: 'false') === 'true',
        ),
    ),
);
S3EOF
        chown "$user:$group" "$config_dir/s3.config.php"
    fi

    # Redis configuration
    if [ -n "${REDIS_HOST:-}" ]; then
        cat > "$config_dir/redis.config.php" <<'REDISEOF'
<?php
$CONFIG = array(
    'memcache.distributed' => '\\OC\\Memcache\\Redis',
    'memcache.locking' => '\\OC\\Memcache\\Redis',
    'redis' => array(
        'host' => getenv('REDIS_HOST'),
        'port' => (int)(getenv('REDIS_HOST_PORT') ?: 6379),
    ),
);
if (getenv('REDIS_HOST_PASSWORD')) {
    $CONFIG['redis']['password'] = getenv('REDIS_HOST_PASSWORD');
}
REDISEOF
        chown "$user:$group" "$config_dir/redis.config.php"
    fi

    # APCu local cache
    cat > "$config_dir/apcu.config.php" <<'APCUEOF'
<?php
$CONFIG = array(
    'memcache.local' => '\\OC\\Memcache\\APCu',
);
APCUEOF
    chown "$user:$group" "$config_dir/apcu.config.php"

    # Apache pretty URLs
    cat > "$config_dir/apache-pretty-urls.config.php" <<'URLEOF'
<?php
$CONFIG = array(
    'htaccess.RewriteBase' => '/',
);
URLEOF
    chown "$user:$group" "$config_dir/apache-pretty-urls.config.php"

    # Reverse proxy / overwrite protocol
    if [ -n "${OVERWRITEPROTOCOL:-}" ]; then
        cat > "$config_dir/reverse-proxy.config.php" <<PROXYEOF
<?php
\$CONFIG = array(
    'overwriteprotocol' => '${OVERWRITEPROTOCOL}',
);
PROXYEOF
        chown "$user:$group" "$config_dir/reverse-proxy.config.php"
    fi

    # Disable web-based updater in container
    cat > "$config_dir/upgrade-disable-web.config.php" <<'UPGRADEEOF'
<?php
$CONFIG = array(
    'upgrade.disable-web' => true,
);
UPGRADEEOF
    chown "$user:$group" "$config_dir/upgrade-disable-web.config.php"
}

# --- Main Logic ---

if [[ "$1" == "httpd"* ]] || [ "$1" = "php-fpm" ]; then

    write_php_config
    configure_redis_session

    # Resolve env vars (support _FILE variants)
    file_env 'POSTGRES_HOST'
    file_env 'POSTGRES_DB' 'nextcloud'
    file_env 'POSTGRES_USER'
    file_env 'POSTGRES_PASSWORD'
    file_env 'NEXTCLOUD_ADMIN_USER'
    file_env 'NEXTCLOUD_ADMIN_PASSWORD'
    file_env 'REDIS_HOST'
    file_env 'REDIS_HOST_PORT' '6379'
    file_env 'REDIS_HOST_PASSWORD'

    # Run installation/upgrade under lock
    (
        if ! flock -n 9; then
            echo "Waiting for other Nextcloud initialization to finish..."
            flock 9
        fi

        installed_version="0.0.0.0"
        if [ -f /var/www/html/version.php ]; then
            installed_version=$(php -r 'require "/var/www/html/version.php"; echo implode(".", $OC_Version);')
        fi

        image_version=$(php -r 'require "/usr/src/nextcloud/version.php"; echo implode(".", $OC_Version);')

        if version_greater "$installed_version" "$image_version"; then
            echo "Cannot downgrade Nextcloud from $installed_version to $image_version"
            exit 1
        fi

        if version_greater "$image_version" "$installed_version"; then
            echo "Initializing Nextcloud $image_version ..."

            if [ "$installed_version" != "0.0.0.0" ]; then
                echo "Upgrading Nextcloud from $installed_version ..."
            fi

            # Sync Nextcloud source to web root
            rsync -rlDog --chown "$user:$group" \
                --delete \
                --exclude-from=/upgrade.exclude \
                /usr/src/nextcloud/ /var/www/html/

            # Ensure key directories exist and have content
            for dir in config data custom_apps themes; do
                if [ ! -d "/var/www/html/$dir" ] || [ -z "$(ls -A "/var/www/html/$dir" 2>/dev/null)" ]; then
                    if [ -d "/usr/src/nextcloud/$dir" ]; then
                        rsync -rlDog --chown "$user:$group" \
                            "/usr/src/nextcloud/$dir/" "/var/www/html/$dir/"
                    else
                        mkdir -p "/var/www/html/$dir"
                    fi
                fi
            done

            # Always sync version.php
            rsync -rlDog --chown "$user:$group" \
                /usr/src/nextcloud/version.php /var/www/html/version.php

            # Write config snippets from environment
            write_config_snippets

            if [ "$installed_version" = "0.0.0.0" ]; then
                echo "New Nextcloud instance"

                # Auto-install if admin credentials are provided
                if [ -n "${NEXTCLOUD_ADMIN_USER:-}" ] && [ -n "${NEXTCLOUD_ADMIN_PASSWORD:-}" ]; then

                    install_options=()

                    if [ -n "${POSTGRES_HOST:-}" ]; then
                        file_env 'POSTGRES_DB' 'nextcloud'
                        file_env 'POSTGRES_USER'
                        file_env 'POSTGRES_PASSWORD'

                        install_options+=(
                            --database pgsql
                            --database-name "$POSTGRES_DB"
                            --database-user "$POSTGRES_USER"
                            --database-pass "$POSTGRES_PASSWORD"
                            --database-host "$POSTGRES_HOST"
                        )
                    fi

                    echo "Installing with provided admin credentials..."

                    max_retries=10
                    for i in $(seq 1 $max_retries); do
                        if run_as "php /var/www/html/occ maintenance:install \
                            --admin-user '${NEXTCLOUD_ADMIN_USER}' \
                            --admin-pass '${NEXTCLOUD_ADMIN_PASSWORD}' \
                            ${install_options[*]:-}"; then
                            break
                        fi
                        echo "Install attempt $i/$max_retries failed, retrying..."
                        sleep 10
                    done

                    # Set trusted domains
                    if [ -n "${NEXTCLOUD_TRUSTED_DOMAINS:-}" ]; then
                        local_index=1
                        for domain in $NEXTCLOUD_TRUSTED_DOMAINS; do
                            run_as "php /var/www/html/occ config:system:set trusted_domains $local_index --value='$domain'"
                            local_index=$((local_index + 1))
                        done
                    fi

                else
                    echo "Next step: Access your instance to finish the web-based installation!"
                    echo "Hint: Set NEXTCLOUD_ADMIN_USER and NEXTCLOUD_ADMIN_PASSWORD to automate."
                fi

            else
                # Upgrade existing installation
                run_as "php /var/www/html/occ upgrade"
                run_as "php /var/www/html/occ db:add-missing-indices"
                run_as "php /var/www/html/occ db:add-missing-columns"
                run_as "php /var/www/html/occ db:add-missing-primary-keys"
            fi

            echo "Initializing finished"
        fi

        # Ensure config snippets are up to date even if version hasn't changed
        write_config_snippets

    ) 9> /var/www/html/nextcloud-init-sync.lock

    run_hook_scripts "before-starting"

    # Start php-fpm in the background before httpd
    echo "Starting php-fpm..."
    php-fpm --daemonize
fi

exec "$@"
